INSERT INTO FILM_LOCATION (ID, TITLE, RELEASE_YEAR, LOCATION) VALUES (1, 180,2011, 'Epic Roasthouse (399 Embarcadero)');
INSERT INTO FILM_LOCATION (ID, TITLE, RELEASE_YEAR, LOCATION) VALUES (2, 180,2011, 'Mason & California Streets (Nob Hill)');
